[tool.poetry]
name = "steam-forum"
version = "0.1.0"
description = ""
authors = ["ramazanix <ramazanui2002@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
authlib = "^1.3.1"
fastapi = "^0.111.0"
steam = "^1.4.4"
uvicorn = "^0.30.1"
itsdangerous = "^2.2.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
